# Generated by Django 5.2.3 on 2025-07-07 14:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logo_generator', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ColorScheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('primary_color', models.CharField(max_length=7)),
                ('secondary_color', models.CharField(max_length=7)),
                ('accent_color', models.CharField(blank=True, max_length=7)),
                ('is_premium', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='LogoStyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('preview_image', models.ImageField(blank=True, upload_to='style_previews/')),
                ('is_premium', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='generatedlogo',
            name='download_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='generatedlogo',
            name='vector_file',
            field=models.FileField(blank=True, upload_to='vectors/'),
        ),
        migrations.AddField(
            model_name='logorequest',
            name='include_business_card',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='logorequest',
            name='include_letterhead',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='logorequest',
            name='include_social_media',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='logorequest',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='logorequest',
            name='priority',
            field=models.CharField(choices=[('standard', 'Standard'), ('express', 'Express (24h)'), ('urgent', 'Urgent (6h)')], default='standard', max_length=20),
        ),
        migrations.AddField(
            model_name='logorequest',
            name='tagline',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='logorequest',
            name='variations_count',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_premium',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='subscription_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='credits',
            field=models.IntegerField(default=3),
        ),
        migrations.CreateModel(
            name='BusinessCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('front_design', models.ImageField(upload_to='business_cards/')),
                ('back_design', models.ImageField(blank=True, upload_to='business_cards/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('logo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logo_generator.generatedlogo')),
            ],
        ),
        migrations.AlterField(
            model_name='logorequest',
            name='color_scheme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logo_generator.colorscheme'),
        ),
        migrations.AlterField(
            model_name='logorequest',
            name='industry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logo_generator.industry'),
        ),
        migrations.CreateModel(
            name='LogoFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('logo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logo_generator.generatedlogo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AIPromptTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('template', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('industry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='logo_generator.industry')),
                ('style', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logo_generator.logostyle')),
            ],
        ),
        migrations.AlterField(
            model_name='logorequest',
            name='style',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logo_generator.logostyle'),
        ),
        migrations.CreateModel(
            name='LogoVariation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variation_type', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='variations/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('logo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variations', to='logo_generator.generatedlogo')),
            ],
        ),
        migrations.CreateModel(
            name='SocialMediaKit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook_cover', models.ImageField(upload_to='social_media/')),
                ('instagram_post', models.ImageField(upload_to='social_media/')),
                ('twitter_header', models.ImageField(upload_to='social_media/')),
                ('linkedin_banner', models.ImageField(upload_to='social_media/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('logo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logo_generator.generatedlogo')),
            ],
        ),
    ]
