services:
  - type: web
    name: logomaker
    env: python
    runtime: python-3.11
    startCommand: "gunicorn --bind 0.0.0.0:$PORT logomaker.wsgi:application"
    plan: free
    envVars:
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4