services:
  - type: web
    name: logomaker
    env: python
    runtime: python-3.10
    buildCommand: "./build.sh"
    startCommand: "gunicorn logomaker.wsgi:application --bind 0.0.0.0:$PORT"
    plan: free
    envVars:
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: PYTHON_VERSION
        value: 3.10.12