services:
  - type: web
    name: logomaker
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn logomaker.wsgi:application
    envVars:
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        generateValue: true