# Generated by Django 5.2.3 on 2025-07-07 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('logo_generator', '0002_colorscheme_industry_logostyle_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('version', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('api_endpoint', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AIAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('total_generations', models.IntegerField(default=0)),
                ('successful_generations', models.IntegerField(default=0)),
                ('failed_generations', models.IntegerField(default=0)),
                ('average_generation_time', models.FloatField(default=0)),
                ('most_popular_style', models.CharField(blank=True, max_length=50)),
                ('most_popular_industry', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'unique_together': {('date',)},
            },
        ),
        migrations.CreateModel(
            name='GenerationTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('progress', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('ai_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ai_engine.aimodel')),
                ('logo_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logo_generator.logorequest')),
            ],
        ),
        migrations.CreateModel(
            name='AIPrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt_text', models.TextField()),
                ('negative_prompt', models.TextField(blank=True)),
                ('style_weight', models.FloatField(default=1.0)),
                ('color_weight', models.FloatField(default=1.0)),
                ('creativity_level', models.FloatField(default=0.7)),
                ('generation_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ai_engine.generationtask')),
            ],
        ),
    ]
