# Generated by Django 5.2.3 on 2025-07-07 16:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIModelConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('model_path', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('default_steps', models.IntegerField(default=30)),
                ('default_cfg_scale', models.FloatField(default=7.5)),
                ('default_sampler', models.CharField(default='DPM++ 2M Karras', max_length=50)),
                ('average_generation_time', models.FloatField(blank=True, null=True)),
                ('success_rate', models.FloatField(default=0.0)),
                ('total_generations', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ColorScheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('primary_color', models.CharField(help_text='Hex color code', max_length=7)),
                ('secondary_color', models.CharField(blank=True, max_length=7)),
                ('accent_color', models.CharField(blank=True, max_length=7)),
                ('description', models.TextField(blank=True)),
                ('prompt_keywords', models.CharField(help_text='Keywords for AI prompt', max_length=200)),
                ('is_premium', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Industries',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LogoStyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('prompt_template', models.TextField(help_text='Base prompt template for this style')),
                ('negative_prompt', models.TextField(blank=True, help_text='Negative prompt for this style')),
                ('preview_image', models.ImageField(blank=True, upload_to='style_previews/')),
                ('is_premium', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SystemStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('total_requests', models.IntegerField(default=0)),
                ('successful_generations', models.IntegerField(default=0)),
                ('failed_generations', models.IntegerField(default=0)),
                ('unique_users', models.IntegerField(default=0)),
                ('total_downloads', models.IntegerField(default=0)),
                ('average_generation_time', models.FloatField(default=0.0)),
                ('most_popular_style', models.CharField(blank=True, max_length=100)),
                ('most_popular_industry', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'System Statistics',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='LogoRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_key', models.CharField(blank=True, help_text='For anonymous users', max_length=40)),
                ('business_name', models.CharField(max_length=200)),
                ('business_description', models.TextField(blank=True)),
                ('additional_colors', models.CharField(blank=True, max_length=200)),
                ('custom_prompt', models.TextField(blank=True, help_text='Additional prompt details')),
                ('final_prompt', models.TextField(blank=True, help_text='Generated final prompt')),
                ('negative_prompt', models.TextField(blank=True)),
                ('variations_count', models.IntegerField(default=4)),
                ('priority', models.CharField(choices=[('standard', 'Standard'), ('express', 'Express (24h)'), ('urgent', 'Urgent (6h)')], default='standard', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('color_scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logo_app.colorscheme')),
                ('industry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logo_app.industry')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('style', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logo_app.logostyle')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GeneratedLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='logos/%Y/%m/')),
                ('thumbnail', models.ImageField(blank=True, upload_to='thumbnails/%Y/%m/')),
                ('seed', models.BigIntegerField(blank=True, null=True)),
                ('steps', models.IntegerField(default=30)),
                ('cfg_scale', models.FloatField(default=7.5)),
                ('sampler', models.CharField(blank=True, max_length=50)),
                ('model_used', models.CharField(blank=True, max_length=100)),
                ('generation_time', models.FloatField(blank=True, help_text='Time in seconds', null=True)),
                ('quality_score', models.IntegerField(default=0, help_text='AI quality assessment 0-100')),
                ('user_rating', models.IntegerField(blank=True, help_text='User rating 1-5', null=True)),
                ('view_count', models.IntegerField(default=0)),
                ('download_count', models.IntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_public', models.BooleanField(default=True)),
                ('file_size', models.IntegerField(blank=True, help_text='File size in bytes', null=True)),
                ('image_width', models.IntegerField(blank=True, null=True)),
                ('image_height', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logos', to='logo_app.logorequest')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PromptHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=40)),
                ('raw_prompt', models.TextField()),
                ('final_prompt', models.TextField()),
                ('negative_prompt', models.TextField(blank=True)),
                ('success_rate', models.FloatField(default=0.0, help_text='Success rate of this prompt')),
                ('usage_count', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('industry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='logo_app.industry')),
                ('style', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='logo_app.logostyle')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=200)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('credits', models.IntegerField(default=3)),
                ('is_premium', models.BooleanField(default=False)),
                ('premium_expires', models.DateTimeField(blank=True, null=True)),
                ('total_logos_generated', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LogoFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=40)),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('comment', models.TextField(blank=True)),
                ('is_helpful', models.BooleanField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('logo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='logo_app.generatedlogo')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('logo', 'user', 'session_key')},
            },
        ),
    ]
